---
title: "PenEstim_OC_PALB2_vNK_not_remove_proband"
author: "Koki Takabatake"
date: "2024-10-13"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(penetrance)
library(ggplot2)
library(ggridges)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(GGally)

set.seed(27)
```



```{r }
# Load data
load("/Users/kokitakabatake/Partners HealthCare Dropbox/BayesMendel/Projects/Active/NK_PenetranceEstimation/5_Data/PALB2_carrier_families.RData")
load("/Users/kokitakabatake/Partners HealthCare Dropbox/Koki Takabatake/PanelPRODatabase.rda")
dat <- carrier_families_list

PanelPRO<-PanelPRODatabase
```





```{r est1, echo=TRUE, cache=FALSE}
# Data Preperation in the right format
for (i in seq_along(dat)) {
  if ("ID" %in% colnames(dat[[i]])) {
    colnames(dat[[i]])[colnames(dat[[i]]) == "PedigreeID"] <- "FamilyID"
  }
}
for (i in seq_along(dat)) {
  # Add a new column "PedigreeID" with the list number
  dat[[i]]$PedigreeID <- i
}

# Change "isAffCOL" to "isAff" if "isAffCOL" is a column
for (i in seq_along(dat)) {
  if ("isAffOC" %in% colnames(dat[[i]])) {
    colnames(dat[[i]])[colnames(dat[[i]]) == "isAffOC"] <- "isAff"
  }
}
for (i in seq_along(dat)) {
  if ("AgeOC" %in% colnames(dat[[i]])) {
    colnames(dat[[i]])[colnames(dat[[i]]) == "AgeOC"] <- "Age"
  }
}
for (i in seq_along(dat)) {
  if ("PALB2" %in% colnames(dat[[i]])) {
    colnames(dat[[i]])[colnames(dat[[i]]) == "PALB2"] <- "geno"
  }
}

# Set the prior
prior_params <- list(
    asymptote = list(g1 = 3, g2 = 7),
    threshold = list(min = 5, max = 40),
    median = list(m1 = 2, m2 = 2),
    first_quartile = list(q1 = 6, q2 = 3)
)

# Use the SEER baseline (imported seperately)
baseline <- PanelPRO$Penetrance["Ovarian","SEER","All_Races",,,"Net"]
# Adjust Format
baseline_df <- as.data.frame(t(baseline))
colnames(baseline_df) <- c("Female")
baseline_df$Age <- as.numeric(rownames(baseline_df))
baseline_df <- baseline_df[, c("Female")]
#allele frequency also in PanelProDatabase
```

str(baseline_df)


```{r}
#Run Estimation procedure with default prior setting 
#Main Estimation for Female

system.time(out_OC_PALB2 <- penetrance(
    pedigree  = dat, twins = NULL,n_chains = 1, n_iter_per_chain = 10000, ncores = 6, 
    baseline_data = baseline_df, af  = 0.000057, 
  prior_params = prior_params_default, var=c(0.1, 2, 5, 5), burn_in = 0.1, median_max = TRUE,
    age_imputation  = FALSE, remove_proband = FALSE, sex_specific=FALSE
))

save(out_OC_PALB2, file = "out_OC_PALB2_not_remove_proband.Rdata")
```

